### PR TITLE
Honeyform exception list

### LINKED ISSUE #71: Add honeyform "exclude pages" setting field
@erikyo If it's not a problem I was going to add a custom option field for the excluded pages in the admin panel so the user can exclude pages as he likes

_Originally posted by @gardenboi in https://github.com/erikyo/cf7-antispam/issues/69#issuecomment-1826065596_

### PR DESCRIPTION
**Pull request by gardenboi**
closes #71

### CODE REVIEW

File: admin/CF7_AntiSpam_Admin_Customizations.php [hunk 1]
```diff
@@ -1462,6 +1474,55 @@ public function cf7a_honeyform_position_callback() {
...
+								%s
+								</select>
+								<br/>
+								<div class="remove-list">< Remove</div>
+							  </div>
+						 </div>
+					 </div>',
+					$options,
+					$str_excluded
+		);
```
Comment (erikyo) [inline admin/CF7_AntiSpam_Admin_Customizations.php:1523]:
```suggestion
		printf(
			'<div class="honeyform-container">
						 <div class="row">
							  <div class="add">
								<select name="add" multiple class="form-control add-select">
								  %s
								</select>
								<div class="honeyform-action add-list">%s ></div>
							  </div>
							  <div class="remove">
								<select id="honeyform_excluded_pages" name="cf7a_options[honeyform_excluded_pages][]" multiple="multiple" class="form-control remove-select" >
								%s
								</select>
								<div class="honeyform-action remove-list">< %s</div>
							  </div>
						 </div>
					 </div>',
					$options,
					__( 'Add', 'cf7-antispam' ),
					$str_excluded,
					__( 'Remove', 'cf7-antispam' ),
		);
```

please provide the translated text for each one added

File: admin/CF7_AntiSpam_Admin_Customizations.php [hunk 2]
```diff
@@ -1091,6 +1102,7 @@ public function cf7a_sanitize_options( $input ) {
 		/* honeyform */
 		$new_input['check_honeyform']    = isset( $input['check_honeyform'] ) ? 1 : 0;
 		$new_input['honeyform_position'] = ! empty( $input['honeyform_position'] ) ? sanitize_title( $input['honeyform_position'] ) : 'wp_body_open';
+		$new_input['honeyform_excluded_pages'] = ! empty( $input['honeyform_excluded_pages'] ) ?  array_map('number_format', $input['honeyform_excluded_pages']) : '';
```
Comment (erikyo) [inline admin/CF7_AntiSpam_Admin_Customizations.php:1105]: you should validate the the array removing any non uint found in it

File: src/settings/settings.scss [hunk 3]
```diff
@@ -88,6 +88,28 @@ $color__info: $color__blue;
...
+			.add,
+			.remove {
+				flex: 1;
+				select {
+					width: 100%;
+					min-height: 120px;
+				}
+				div {
+					text-align: center;
+					border: #8c8f94 solid 1px;
```
Comment (erikyo) [inline src/settings/settings.scss:107]:
```suggestion
					border: $color__dark-grey solid 1px;
```

please use the colors already available

File: admin/CF7_AntiSpam_Admin_Customizations.php (hunk 1 above)
Comment (erikyo) [reply admin/CF7_AntiSpam_Admin_Customizations.php:1523]: FYI, you can even add an emoji's arrow (like this one ➡️) or the unicode arrow (➔)

File: src/settings/settings.scss [hunk 4]
```diff
@@ -88,6 +88,28 @@ $color__info: $color__blue;
...
 
+	// Style for honeyform exclude pages
+	.honeyform-container {
+
+		.row {
+			display: flex;
+			flex-wrap: wrap;
+
+			.add,
+			.remove {
```
Comment (erikyo) [inline src/settings/settings.scss:99]:
```suggestion

			.honeyform-action {
				margin-top: 8px;
			}

			.add,
			.remove {
```

Comment (erikyo) [reply src/settings/settings.scss:99]: 👆 replaces the `<br/>` below the selects

**Review by erikyo — CHANGES_REQUESTED** [review]

**Review by erikyo — APPROVED** [review]
well done young padawan, great job!
