### PR TITLE
FIx Lang locale incoherence

### LINKED ISSUE #44: False positives due to language_incoherence and missing language field
We're noticing quite a bit of false positive spam messages on our website due to the language functions in the plugin. I've currently disabled the language verification on the website, but would like to be able to add this extra check back in the future.

CF7 is being used for user to user messages on our website.

The most common spam log messages we find for false positive spam messages are along the lines of "language_field: missing language field" and "language_incoherence: languages detected not coherent (nl vs fr-be-en) or (nl vs fr)".

There is no language field in the contact form and adding a hard coded hidden language field wouldn't help either, as our website is being used in Belgium (and the Netherlands). Belgium is a multilingual country, so we would already exclude 3 of our national languages then. I don't know if I'm missing a specific setting here or if this is most likely a bug.

Either way, then there's also the issue with the language incoherence between the browser and the website language. We had 'en', 'nl', 'de' and 'fr' as allowed languages in the language settings, but they still seemed to get flagged anyway. Next, then there's the doubt that 'be' (see error message above) would stand for Belgium (the country, not the language, as there is no "Belgian" language. We speak nl-BE, fr-BE, de-BE and en-UK or en-US). If 'be' was the correct language code, then it would stand for Belarusian. I highly doubt that either the user has their browser in Belarusian, for this specific case, and our website doesn't have any Belarusian translations either. Our website is only available in Dutch (nl-BE) at the moment.

Lastly, this is not part of the bug, but would be great to know. Would the language settings pose a problem when a website is multilingual, seeing that there are some inconsistencies (as far as we know right now). We're looking into adding French, German and English as extra languages to our website in the near future.

### PR DESCRIPTION
**Pull request by gardenboi**
image

### The above representation is a summary of the code implementation.

Closes #44

**In this commit the following has been updated:**
- Assignations in Filters class (the logic is almost the same)
- added and modified Filters functions
- updated the Filter Tests accordingly
- updated the description in the admin settings

Now the language and locale are treated as separate entities, which are present on separate associative(key/value) arrays under the refactored option `language` now called
`languages_locales` ===> `allowed / disallowed` ===> `languages / locales` 

Now the end user can do the following:
- write languages as lower case 2 pair letters [ISO 639-1](https://www.loc.gov/standards/iso639-2/php/code_list.php)
- write languages as upper case 2 pair letters [ISO 3166-2](https://www.iso.org/obp/ui/#search)
- write language and locales together ex: `it-IT`

this means the settings field in the admin can be like the following:
**EX1**
```
it-IT
```
### EX2
```
it
IT
```
And still lead to the same behaviour

This PR will probably need some fixes, let me know @erikyo for further corrections.
Also I'd like to know @johnhooks if the explanations are clear or require better explanations.

### CODE REVIEW

File: engine/CF7_AntiSpam_Updater.php [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+ * @subpackage CF7_AntiSpam/includes
+ * @author     Codekraft Studio <info@codekraft.it>, gardenboi
+ */
+
+use CF7_AntiSpam\Admin\CF7_AntiSpam_Admin_Tools;
+use CF7_AntiSpam\Core\CF7_AntiSpam_Filters;
+/* TODO: delete the function in the activation script and write a new one that splits only the ";"
+	Reason: the "languages_locales" and the old "languages" are the same string[] type, the actual code
+	is splitted in the Filters class, therefore delete part of the procedure.
+*
```
Comment (erikyo) [inline engine/CF7_AntiSpam_Updater.php:20]: ?

**Review by erikyo — CHANGES_REQUESTED** [review]

File: core/CF7_AntiSpam_Filters.php [hunk 2]
```diff
@@ -702,7 +756,12 @@ public function cf7a_spam_filter( $spam ) {
 					/* check if the language is allowed and if is disallowed */
 					$client_languages = array_unique( array_merge( $languages['browser'], $languages['accept'] ) );
 
-					$language_disallowed = $this->cf7a_check_language_allowed( $client_languages, $languages_disallowed, $languages_allowed );
+					/* Checks sender has a blacklisted ip address */
+					$languages_allowed    = isset( $options['languages_locales']['allowed'] ) ? $this->cf7a_get_language_locales( $options['languages_locales']['allowed'], 'languages' ) : array();
+					$languages_disallowed = isset( $options['languages_locales']['disallowed'] ) ? $this->cf7a_get_language_locales( $options['languages_locales']['disallowed'], 'languages' ) : array();
+
+
+					$language_disallowed = $this->cf7a_check_languages_locales_allowed( $client_languages, $languages_disallowed, $languages_allowed );
```
Comment (johnhooks) [inline core/CF7_AntiSpam_Filters.php:764]: Is this checking the "sender has a blacklisted ip address?", it doesn't read that way.

**Review by johnhooks — COMMENTED** [review]
@gardenboi I left a few comments. Though I'm not familiar with the code being changed, I'll defer to @erikyo for approval. My general suggestions:

- If formatting changes need to happen in PRs, it's nice to do them before in a separate PR beforehand, having it mix with logical changes make it harder to review.
- I suggest breaking some of the larger functions into smaller ones, makes it easier to understand in code review and also when coming back to it later.

File: core/CF7_AntiSpam_Filters.php [hunk 3]
```diff
@@ -237,33 +241,84 @@ public function cf7a_cron_unban() {
...
+						if ( ! empty( $l ) ) {
+							$carry[] = $l;
+						}
+
+						return $carry;
+					} 
+				) 
+			) 
+		);
+	}
```
[the remark this answers is not in the document]
Comment (gardenboi) [reply core/CF7_AntiSpam_Filters.php]: yup, I just made an external function, not many PHPers are used to functional approach

File: core/CF7_AntiSpam_Filters.php [hunk 4]
```diff
@@ -237,33 +241,81 @@ public function cf7a_cron_unban() {
...
+							$l = $this->cf7a_check_length_exclusive( $item, 1 );
+						}
+						if ( ! empty( $l ) ) {
+							$carry[] = $l;
+						}
+						return $carry;
+					}
+				)
+			)
+		);
```
Comment (erikyo) [inline core/CF7_AntiSpam_Filters.php:289]:
```suggestion
	$languages = [];
	foreach ( $option as $item ) {
		$carry = is_array( $carry ) ? $carry : array();
		if ( $key == 'languages' ) {
			$l = $this->cf7a_check_length_exclusive( $item, 0 );
		} elseif ( $key == 'locales' ) {
			$l = $this->cf7a_check_length_exclusive( $item, 1 );
		}
		if ( ! empty( $l ) ) {
			$languages[] = $l;
		}
	}
	return array_values( array_unique( $languages ) );
```

Comment (erikyo) [reply core/CF7_AntiSpam_Filters.php:289]: In this way seems safer and less overcomplicated!

File: core/CF7_AntiSpam_Filters.php [hunk 5]
```diff
@@ -237,33 +241,81 @@ public function cf7a_cron_unban() {
 		return true;
 	}
 
+	public function cf7a_check_length_exclusive( $el, $n ) {
```
Comment (erikyo) [inline core/CF7_AntiSpam_Filters.php:244]:
```suggestion
	/**
	 * Checks the length of a string and returns a specific part of it based on a given index.
	 *
	 * @param string $el The input string to be checked.
	 * @param int $n The index used to retrieve a specific part of the string.
	 * @return string The extracted part of the string based on the given index, or an empty string if the conditions are not met.
	 */
	public function cf7a_check_length_exclusive( $el, $n ) {
```
	 please add a comment for each function. in this case should be fine

File: core/functions.php [hunk 6]
```diff
@@ -101,13 +130,35 @@ function ( $res, $el ) {
...
 				}
+
+				return $res;
+			},
+			array()
+		)
+	);
+}
+
+function cf7a_get_accept_locales_array( $locales ) {
```
Comment (erikyo) [inline core/functions.php:147]:
```suggestion
/**
 * Generates an array of accepted locales based on the given input.
 *
 * @param string $locales A comma-separated list of locales.
 * @return array An array of accepted locales.
 */
function cf7a_get_accept_locales_array( $locales ) {
```

Comment (erikyo) [inline core/functions.php:147]: is this an unused function? I cannot find where it was used anywere 🧐

File: cf7-antispam.php [hunk 7]
```diff
@@ -137,8 +137,13 @@ function cf7_antispam_register_service() {
 
 
 function run_cf7a() {
-	$enabled = get_option( 'cf7a_options' );
-	if ( $enabled && ! empty( $enabled['cf7a_enable'] ) ) {
+
+	$options = get_option( 'cf7a_options' );
+
+	if ( $options && ! empty( $options['cf7a_enable'] ) ) {
```
Comment (erikyo) [inline cf7-antispam.php:143]: I was wondering if it wouldn't be better to use !empty($options) instead of $options... although get_option can return false|mixed so, even if there are no options at all, it wouldn't be a real issue

**Review by erikyo — APPROVED** [review]
